# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: workflow-config
#   labels:
#     app: skipper-workflow
# data:
#   LOGGER_URL: http://skipper-logger:5001/api/v1/skipper/logger/log_workflow

apiVersion: v1
kind: Pod
metadata:
  name: post-app
spec:
  containers:
        - image: post-app:latest
          name: post-app
          imagePullPolicy: IfNotPresent
          # livenessProbe:
          #   httpGet:
          #     path: /api/v1/skipper/workflow/
          #     port: 5000
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 1
          #   periodSeconds: 600
          #   failureThreshold: 3
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
