apiVersion: v1
kind: Pod
metadata:
  name: fast-db
  labels:
    app: fast-db
spec:
  containers:
  - name: fast-db
    image: postgres
    imagePullPolicy: IfNotPresent
    env:
    - name: POSTGRES_PASSWORD
      value: postgres
    - name: POSTGRES_DB
      value: fastapi
      # valueFrom:
      #   secretKeyRef:
      #   - name: postgres-secret-config
      #     key: password
      #   - name: PGDATA
      #     value: /var/lib/postgresql/data/pgdata
    ports:
      - containerPort: 5432
    volumeMounts:
      - mountPath: /var/lib/postgresql/data
        name: postgres-pv-storage
  volumes:
    - name: postgres-pv-storage
      persistentVolumeClaim:
        claimName: postgres-pv-claim